apiVersion: v1
kind: Secret
metadata:
  name: sage-restapi
type: Opaque
stringData:
    minio_accesskey: ""
    minio_secretkey: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sage-restapi
  namespace: sage
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-restapi
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sage-restapi
  template:
    metadata:
      labels:
        k8s-app: sage-restapi
    spec:
      containers:
      - name: sage-restapi
        image: iperezx/sage-restapi:latest
        env:
          - name: SAGERESTAPI_URL
            value: "sage-minio.nautilus.optiputer.net"
          - name: MINIO_ACCESSKEY
            valueFrom:
                secretKeyRef:
                  name: sage-restapi
                  key: minio_accesskey
          - name: MINIO_SECRETKEY
            valueFrom:
                secretKeyRef:
                  name: sage-restapi
                  key: minio_secretkey
          - name: WORKDIR
            value: "/app/"
          #Taken from sage-ui.yaml
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: sage-ui-mysql-env
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sage-ui-mysql-env
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sage-ui-mysql-env
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sage-ui-mysql-env
                key: MYSQL_DATABASE
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: sage-ui-mysql-env
                key: MYSQL_HOST          
        args: [$(SAGERESTAPI_URL), $(MINIO_ACCESSKEY), $(MINIO_SECRETKEY), $(WORKDIR)]
        resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              memory: 2Gi
              cpu: 1
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
            - mountPath: /var/www/html
              name: sage-restapi
            - mountPath: /var/lib/mysql
              name: sage-ui-db
        imagePullPolicy: Always
      volumes:
        - name: sage-restapi
          persistentVolumeClaim:
              claimName: sage-restapi
        - name: sage-ui-db
          persistentVolumeClaim:
            claimName: sage-ui-db
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sage-restapi
  labels:
    service: sage-restapi
spec:
  selector:
    k8s-app: sage-restapi
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sage-restapi
  namespace: sage
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: sage-restapi.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: sage-restapi
          servicePort: 8080

