apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 
  - sage-storage-api.ingress
  
  - sage-storage-api.deployment
  - sage-storage-api.secret
  - sage-storage-api.service

  - sage-storage-db.deployment
  - sage-storage-db.pvc
  - sage-storage-db.service
  - sage-storage-db.secret


